=== joejcollins/harmony-angel/ConsoleApp/Input/CookML.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Schema for Cookbook Markup Language -->
<!-- Developed by Joe Collins, joe@bagbatch.co.uk -->
<xsd:schema targetNamespace="http://www.joejcollins.co.uk/CookBook/CookML.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.joejcollins.co.uk/CookBook/CookML.xsd" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0a" id="CookML">
  <xsd:annotation>
    <xsd:documentation xml:lang="en">
			As required by the best practice guidelines:
				1. the default namespace and the target namespase are the same.
				2. version and id attributes have been used in the schema element.
				3. version numbers must be included in instance messages.
			
			The guidelines also suggest:
				1. a Russian Doll design is used for messaging schemas.
		</xsd:documentation>
  </xsd:annotation>
  <xsd:element name="Book">
    <xsd:annotation>
      <xsd:documentation>A message structure cook books.</xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="Menu" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="Recipe" minOccurs="1" maxOccurs="unbounded">
                <xsd:complexType mixed="true">
                  <xsd:sequence>
                    <xsd:element name="Index" minOccurs="0" maxOccurs="unbounded">
                      <xsd:complexType mixed="true">
                        <xsd:sequence>
                          <xsd:element name="Sub" type="xsd:string" minOccurs="0" />
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                    <xsd:element name="Stage" minOccurs="1" maxOccurs="unbounded">
                      <xsd:complexType mixed="true">
                        <xsd:sequence minOccurs="0">
                          <xsd:choice maxOccurs="unbounded">
                            <xsd:element name="Staple" minOccurs="0" maxOccurs="unbounded">
                              <xsd:complexType>
                                <xsd:attribute name="Name" form="unqualified" type="Staple" />
                              </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="Temperature" minOccurs="0" maxOccurs="unbounded">
                              <xsd:complexType>
                                <xsd:attribute name="Level" form="unqualified" type="Temperature" />
                              </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="Utensil" minOccurs="0" maxOccurs="unbounded">
                              <xsd:complexType>
                                <xsd:attribute name="Name" form="unqualified" type="Utensil" />
                              </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="Check" minOccurs="0" maxOccurs="unbounded">
                              <xsd:complexType>
                                <xsd:attribute name="Quantity" form="unqualified" type="xsd:float" />
                                <xsd:attribute name="Unit" form="unqualified" type="Unit" />
                                <xsd:attribute name="Type" form="unqualified" type="Check" />
                                <xsd:attribute name="Process" form="unqualified" type="Process" />
                              </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="Dairy" minOccurs="0" maxOccurs="unbounded">
                              <xsd:complexType>
                                <xsd:attribute name="Quantity" form="unqualified" type="xsd:float" />
                                <xsd:attribute name="Unit" form="unqualified" type="Unit" />
                                <xsd:attribute name="Type" form="unqualified" type="Dairy" />
                                <xsd:attribute name="Process" form="unqualified" type="Process" />
                              </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="Grocery" minOccurs="0" maxOccurs="unbounded">
                              <xsd:complexType>
                                <xsd:attribute name="Quantity" form="unqualified" type="xsd:float" />
                                <xsd:attribute name="Unit" form="unqualified" type="Unit" />
                                <xsd:attribute name="Type" form="unqualified" type="Grocery" />
                                <xsd:attribute name="Process" form="unqualified" type="Process" />
                              </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="Meat" minOccurs="0" maxOccurs="unbounded">
                              <xsd:complexType>
                                <xsd:attribute name="Quantity" form="unqualified" type="xsd:float" />
                                <xsd:attribute name="Unit" form="unqualified" type="Unit" />
                                <xsd:attribute name="Type" form="unqualified" type="Meat" />
                                <xsd:attribute name="Process" form="unqualified" type="Process" />
                              </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="Vegetable" minOccurs="0" maxOccurs="unbounded">
                              <xsd:complexType>
                                <xsd:attribute name="Quantity" form="unqualified" type="xsd:float" />
                                <xsd:attribute name="Unit" form="unqualified" type="Unit" />
                                <xsd:attribute name="Type" form="unqualified" type="Vegetable" />
                                <xsd:attribute name="Process" form="unqualified" type="Process" />
                              </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="Water" minOccurs="0" maxOccurs="unbounded">
                              <xsd:complexType>
                                <xsd:attribute name="Quantity" form="unqualified" type="xsd:float" />
                                <xsd:attribute name="Unit" form="unqualified" type="Unit" />
                                <xsd:attribute name="Type" form="unqualified" type="Water" />
                                <xsd:attribute name="Process" form="unqualified" type="Process" />
                              </xsd:complexType>
                            </xsd:element>
                          </xsd:choice>
                        </xsd:sequence>
                      </xsd:complexType>
                    </xsd:element>
                  </xsd:sequence>
                  <xsd:attribute name="Title" form="unqualified" type="xsd:string" />
                  <xsd:attribute name="Meals" type="Meals" />
                </xsd:complexType>
              </xsd:element>
            </xsd:sequence>
            <xsd:attribute name="Title" form="unqualified" type="xsd:string" />
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
      <xsd:attribute name="Title" form="unqualified" type="xsd:string" />
    </xsd:complexType>
  </xsd:element>
  <!-- Global Definitions -->
  <!-- A restriction on the number of meals a recipe can cover. -->
  <xsd:simpleType name="Meals">
    <xsd:annotation>
      <xsd:documentation>Correct number of meals a recipe can cover</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:integer">
      <xsd:enumeration value="1" />
      <xsd:enumeration value="2" />
    </xsd:restriction>
  </xsd:simpleType>
  <!-- A restriction on the types of processing techniques allowed. -->
  <xsd:simpleType name="Process">
    <xsd:annotation>
      <xsd:documentation>Correct processing techniques</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="chopped" />
      <xsd:enumeration value="crushed" />
      <xsd:enumeration value="crumbled" />
      <xsd:enumeration value="drained" />
      <xsd:enumeration value="grated" />
      <xsd:enumeration value="halved" />
      <xsd:enumeration value="sliced" />
      <xsd:enumeration value="washed" />
    </xsd:restriction>
  </xsd:simpleType>
  <!-- A restriction on the types of staple allowed. -->
  <xsd:simpleType name="Staple">
    <xsd:annotation>
      <xsd:documentation>Correct staples</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="cous cous" />
      <xsd:enumeration value="noodles" />
      <xsd:enumeration value="pasta shapes" />
      <xsd:enumeration value="rice" />
      <xsd:enumeration value="spaghetti" />
      <xsd:enumeration value="potatoes" />
      <xsd:enumeration value="tagliatelli" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="Temperature">
    <xsd:annotation>
      <xsd:documentation>Correct temperature levels</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="low" />
      <xsd:enumeration value="medium" />
      <xsd:enumeration value="high" />
    </xsd:restriction>
  </xsd:simpleType>
  <!-- A restriction on the types of measurement units allowed. -->
  <xsd:simpleType name="Unit">
    <xsd:annotation>
      <xsd:documentation>Correct units of measurement</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="cloves" />
      <xsd:enumeration value="cube" />
      <xsd:enumeration value="ml" />
      <xsd:enumeration value="g" />
      <xsd:enumeration value="tbsp" />
      <xsd:enumeration value="tsp" />
    </xsd:restriction>
  </xsd:simpleType>
  <!-- A restriction on the types of utensil allowed. -->
  <xsd:simpleType name="Utensil">
    <xsd:annotation>
      <xsd:documentation>Correct utensils</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="bowl" />
      <xsd:enumeration value="casserole" />
      <xsd:enumeration value="pan" />
      <xsd:enumeration value="wok" />
    </xsd:restriction>
  </xsd:simpleType>
  <!-- Generated from Ingredients.mdb, subject to change -->
  <!-- A restriction on the types ingredient allowed. -->
  <xsd:simpleType name="Check">
    <xsd:annotation>
      <xsd:documentation>Check types in the database</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="black bean sauce" />
      <xsd:enumeration value="chilli powder" />
      <xsd:enumeration value="flour" />
      <xsd:enumeration value="ground coriander" />
      <xsd:enumeration value="ground cumin" />
      <xsd:enumeration value="marjoram" />
      <xsd:enumeration value="mixed herbs" />
      <xsd:enumeration value="mustard seed" />
      <xsd:enumeration value="oil" />
      <xsd:enumeration value="stock cube" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="Dairy">
    <xsd:annotation>
      <xsd:documentation>Dairy types in the database</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="cheese" />
      <xsd:enumeration value="eggs" />
      <xsd:enumeration value="milk" />
      <xsd:enumeration value="soured cream" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="Grocery">
    <xsd:annotation>
      <xsd:documentation>Grocery types in the database</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="baked beans" />
      <xsd:enumeration value="canned chick peas" />
      <xsd:enumeration value="canned tomatoes" />
      <xsd:enumeration value="cous cous" />
      <xsd:enumeration value="creamed coconut" />
      <xsd:enumeration value="green lentils" />
      <xsd:enumeration value="lasagna" />
      <xsd:enumeration value="noodles" />
      <xsd:enumeration value="pasta shapes" />
      <xsd:enumeration value="peanuts" />
      <xsd:enumeration value="pitta bread" />
      <xsd:enumeration value="raisins" />
      <xsd:enumeration value="self raising flour" />
      <xsd:enumeration value="spaghetti" />
      <xsd:enumeration value="suet" />
      <xsd:enumeration value="tomato puree" />
      <xsd:enumeration value="white rice" />
      <xsd:enumeration value="grated parmesan" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="Meat">
    <xsd:annotation>
      <xsd:documentation>Meat types in the database</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="chicken" />
      <xsd:enumeration value="meat" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="Vegetable">
    <xsd:annotation>
      <xsd:documentation>Vegetable types in the database</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="baking potatoes" />
      <xsd:enumeration value="boiling potatoes" />
      <xsd:enumeration value="cabbage" />
      <xsd:enumeration value="carrots" />
      <xsd:enumeration value="celery" />
      <xsd:enumeration value="garlic" />
      <xsd:enumeration value="green chillis" />
      <xsd:enumeration value="mange tout" />
      <xsd:enumeration value="onions" />
      <xsd:enumeration value="red chillis" />
      <xsd:enumeration value="sweet potatoes" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="Water">
    <xsd:annotation>
      <xsd:documentation>Water types in the database</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="boiling water" />
      <xsd:enumeration value="cold water" />
    </xsd:restriction>
  </xsd:simpleType>
</xsd:schema>

=== joejcollins/harmony-angel/data/raw/RandomRecipes.xml
<?xml version="1.0" encoding="utf-8"?>
<Book xmlns="https://joejcollins.github.io/CookML.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="https://joejcollins.github.io/CookML.xsd ../processed/CookML.xsd">
  <Menu Title="Starters and Sides">
    <Recipe>
      
    <Recipe Title="Pizza Salad">
      <Stage></Stage>
    </Recipe>

  </Menu>


  <Menu Title="Cakes">
    <Recipe Title="Welsh Cakes">
      <Stage>

      </Stage>
    </Recipe>
  </Menu>

  <Menu Title="Biscuits">
    <Recipe Title="Joe's Biscuits">
      <Stage>
        In a
        <Utensil Name="bowl" />
        mix together
        <Grocery Name="plain flour" Quantity="110" Unit="g" />,
        <Grocery Name="plain flour" Quantity="110" Unit="g" />,
        <Grocery Name="oats" Quantity="110" Unit="g" />
        and
        <Grocery Name="sugar" Quantity="30" Unit="g" />.
      </Stage>
      <Stage>
        Rub in
        <Dairy Name="butter" Quantity="30" Unit="g" />.
      </Stage>
      <Stage></Stage>
    </Recipe>
  </Menu>

  <Menu Title="Palegg">
    <Recipe Title="Humous">
      <Stage>
      </Stage>
  </Menu>
  


</Book>
